version = 0.1

[main.deploy.parameters]
stack_name = "gym-saas-cloud-api"
resolve_s3 = true
s3_prefix = "gym-saas-cloud-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[main.global.parameters]
region = "us-east-1"
